### ISSUE TITLE
Boolean type for test passed attribute is not able to distinguish between false and undefined

### ISSUE THREAD

**Issue by timlrx** [cylynx/verifyml#42]
If we set `passed = false`, it is not encoded in the proto file as the default is false.

See related [stackoverflow thread](https://stackoverflow.com/questions/51284839/protobuf-ignoring-bool-and-ints-values-due-to-default)

We need to be able to distinguish between `false`, `true` and `undefined` (default). Can consider changing from `boolean` type to `enum` or `string`.

**Comment by timlrx** [comment]
As discussed, we will prevent users from adding a python test if `passed` or `result` attributes is `None`. This would not prevent users from manually editing it after attaching a test but is a quick fix to the issue.

**Comment by jasonho-lynx** [comment]
Merged fix, closing issue for now
