### ISSUE TITLE
Newer numpy version support

### ISSUE THREAD

**Issue by Johnz86** [cylynx/verifyml#53]
Curently verifyml 0.0.4 requires numpy<=1.20
If you have python 3.10 or newer you have compilation issues.
Could you please update the package with numpy==1.21.5
Which should support deployment on 3.10

**Comment by timlrx** [comment]
Most certainly, will relax the numpy version dependency in the next release.

**Comment by timlrx** [comment]
Published as v0.0.5. Let me know if that works for you. There's a little change in the schema as well so if you were using the old one, you might need to make some changes. 

You can now create/edit model cards with our web tool: https://report.verifyml.com/

Let me know if you have a chance to try it out!

Full change log: https://github.com/cylynx/verifyml/releases/tag/v0.0.5

**Comment by timlrx** [comment]
Closing the issue. Let me know if you encounter any issues with the new build and dependencies.
