### ISSUE TITLE
Is the Model Card Editor Open Source?

### ISSUE THREAD

**Issue by laurensWe** [cylynx/verifyml#63]
The docs also refer to an online model card editor through the following URL: https://report.verifyml.com/. Is the source code to this frontend application also open source? If so, could you provide the link to this project in the README.md?

**Comment by timlrx** [comment]
Hi @laurensWe no it was not open source, sorry about that. I probably would also recommend not to use the current framework - we have since migrated to other approaches e.g. https://github.com/IMDA-BTG/aiverify
